/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datastructuresassignment;

/**
 *
 * @author Jian
 */
public class ListOrder extends javax.swing.JFrame {

    /**
     * Creates new form ListOrder
     */
    public ListOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Leong Wei Jian", "Pakage 1",  new Double(1.0),  new Double(50.0),  new Double(50.0), "Cash"},
                {"Fan Zhi Wei", "Pakage 2",  new Double(2.0),  new Double(40.0),  new Double(80.0), "PayPall"},
                {"Choi Chee Kiem", "Flower ",  new Double(5.0),  new Double(15.0),  new Double(75.0), "Cash"},
                {"Choo Jian Ming", "Flower",  new Double(6.0),  new Double(15.0),  new Double(90.0), "PayPall"},
                {"Chong Chee Tong", "Pakage 2",  new Double(1.0),  new Double(40.0),  new Double(40.0), "Cash"},
                {"Choi Chee Kien", "Flower 2",  new Double(3.0),  new Double(15.0),  new Double(45.0), "Cash"},
                {"Leong Wei Jian", "Pakage 3",  new Double(4.0),  new Double(65.0),  new Double(260.0), "PayPall"},
                {"Choo Jian Ming", "Flower 4",  new Double(3.0),  new Double(10.0),  new Double(30.0), "Cash"},
                {"Fan Zhi Wei", "Flower ",  new Double(4.0),  new Double(15.0),  new Double(60.0), "Cash"},
                {"Chong Chee Tong", "Pakage 1",  new Double(5.0),  new Double(50.0),  new Double(250.0), "PayPall"},
                {"Leong Wei Jian", "Pakage 1",  new Double(1.0),  new Double(50.0),  new Double(50.0), "Cash"},
                {"Fan Zhi Wei", "Pakage 2",  new Double(2.0),  new Double(40.0),  new Double(80.0), "PayPall"},
                {"Choi Chee Kiem", "Flower ",  new Double(5.0),  new Double(15.0),  new Double(75.0), "Cash"},
                {"Choo Jian Ming", "Flower",  new Double(6.0),  new Double(15.0),  new Double(90.0), "PayPall"},
                {"Chong Chee Tong", "Pakage 2",  new Double(1.0),  new Double(40.0),  new Double(40.0), "Cash"},
                {"Choi Chee Kien", "Flower 2",  new Double(3.0),  new Double(15.0),  new Double(45.0), "Cash"},
                {"Leong Wei Jian", "Pakage 3",  new Double(4.0),  new Double(65.0),  new Double(260.0), "PayPall"},
                {"Choo Jian Ming", "Flower 4",  new Double(3.0),  new Double(10.0),  new Double(30.0), "Cash"},
                {"Fan Zhi Wei", "Flower ",  new Double(4.0),  new Double(15.0),  new Double(60.0), "Cash"},
                {"Chong Chee Tong", "Pakage 1",  new Double(5.0),  new Double(50.0),  new Double(250.0), "PayPall"}
            },
            new String [] {
                "Customer Name", "Item", "Quantity", "Unit Price", "Total Pricel", "Pament Method"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jLabel1.setText("Order Picked Up Today");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
